package com.valdemar.desafio.model.entity;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "noticias")
public class Noticia {
	
	private String id;
	private String url;
	private String titulo;
	private String subtitulo;
	private String autor;	
	private Date dataPublicacao;	
	private String conteudo;
	
	public Noticia() {
		//super();
	}
	
	public Noticia(String url, String titulo, String subtitulo, String autor, Date dataPublicacao, String conteudo) {
		//super();
		this.url = url;
		this.titulo = titulo;
		this.subtitulo = subtitulo;
		this.autor = autor;
		this.dataPublicacao = dataPublicacao;
		this.conteudo = conteudo;
	}

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
	
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	
	@DynamoDBAttribute
	public String getTitulo() {
		return titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}
	
	@DynamoDBAttribute
	public String getSubtitulo() {
		return subtitulo;
	}

	public void setSubtitulo(String subtitulo) {
		this.subtitulo = subtitulo;
	}
	
	@DynamoDBAttribute
	public String getAutor() {
		return autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	@DynamoDBAttribute
	public Date getDataPublicacao() {
		return dataPublicacao;
	}

	public void setDataPublicacao(Date dataPublicacao) {
		this.dataPublicacao = dataPublicacao;
	}

	@DynamoDBAttribute
	public String getConteudo() {
		return conteudo;
	}

	public void setConteudo(String conteudo) {
		this.conteudo = conteudo;
	}
	
	@Override
	public String toString() {
		return titulo+ "\n\n" + subtitulo +"\n\n";
	}

}
